### ISSUE TITLE
current namespace is "default" and child errors "Missing namespace" even though it's not missing

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-openshift-connector#751]
**Steps:**
1. ASSERT: use minikube
2. EXEC: apply the following RBAC rules 
```yaml
kubectl apply -f -
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: can-read-pods
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: default
subjects:
  - kind: User
    name: user1
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: can-read-pods
  apiGroup: rbac.authorization.k8s.io
```
3. EXEC: create a new user context and switch to it
```
openssl req -new -key user1.key -out user1.csr -subj "/CN=user1/O=group1"
openssl x509 -req -in user1.csr -CA ~/.minikube/ca.crt -CAkey ~/.minikube/ca.key -CAcreateserial -out user1.crt -days 500
kubectl config set-credentials user1 --client-certificate=user1.crt --client-key=user1.key
kubectl config set-context user1-context --cluster=minikube --user=user1
kubectl config use-context user1-context
```
**Result:**
Resource tree erroneously shows "default" as current namespaces and "Missing namespace" at the same time.
<img width="481" alt="image" src="https://github.com/redhat-developer/intellij-openshift-connector/assets/25126/0e6ef960-788c-4c6f-98df-318ca1708ab2">
