### ISSUE TITLE
telemetry "misc-login" is reported as `extension_name": "IDEA CORE"`

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-openshift-connector#824]
In telemetry we report "misc-login": https://github.com/redhat-developer/intellij-openshift-connector/blob/126eec909c9d5b0ca2e9f35ef4096a8791fb969c/src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java#L882

The extension-name tough is reported as "IDEA_CORE" which is wrong, it should be intellij-openshift-connector

![image](https://github.com/redhat-developer/intellij-openshift-connector/assets/25126/617188c3-0626-4aeb-8a00-5b7dbd3a0086)

```yaml
"properties": {
    "app_name": "IntelliJ IDEA Ultimate Edition",
    "app_version": "2024.1",
    "duration": "00:00:00",
    "extension_name": "IDEA CORE",
    "extension_version": "241.14494.240",
    "is_openshift": "false",
    "java_version": "17.0.10",
    "kubernetes_version": "v1.29.2",
    "openshift_version": "",
    "result": "success"
  },
```
